services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    networks:
      - dokploy-network
    labels:
      - traefik.enable=true

networks:
  dokploy-network:
    external: true
